### ISSUE TITLE
File Preview Component - component not found

### ISSUE THREAD

**Issue by amshehzad** [ahmed-aliraqi/laravel-file-uploader#3]
Hi, 
Thank you for such an amazing component!

However, I read the readme file and used the file-uploader and it's working perfectly fine.
but when I try to use `file-preview` component I get the error that the compoenent is not registered.

Thank you

**Comment by ahmed-aliraqi** [comment]
Thanks for reporting, please make sure that you are using the last version. you should remove `node_modules` directory and run `npm install` then `npm run dev`
